### ISSUE TITLE
Move to an org

### ISSUE THREAD

**Issue by dpsanders** [JuliaTeX/TreeView.jl#11]
I would be more than happy for this package to live at a suitable organisation if that would make things easier.

cc @tawheeler

**Comment by tawheeler** [comment]
I think we're going to create a juliaTeX org.

**Comment by dpsanders** [comment]
Great idea!

**Comment by tawheeler** [comment]
Please feel free to move the package over (you're the owner) to [JuliaTeX](https://github.com/JuliaTeX) at your convenience :)
