### ISSUE TITLE
Tree not shown

### ISSUE THREAD

**Issue by xgdgsc** [JuliaTeX/TreeView.jl#15]
Running the example doesn' t work for me. The tree is not shown. While using TikzGraphs works. What could be the reason?

![deepinscreenshot_select-area_20181205121221](https://user-images.githubusercontent.com/1189869/49489652-0dc3a880-f887-11e8-9fe1-6b26956a7aff.png)

**Comment by dpsanders** [comment]
Which version of Julia are you using? And what environment or editor is that running in?

**Comment by dpsanders** [comment]
Could you try the master branch (assuming you're on Julia 1.0):

`]add TreeView#master`

**Comment by xgdgsc** [comment]
Thanks. I' m using julia 1.0.2 in jupyter notebook. master works for me.
