### ISSUE TITLE
Way to pass nested dict with string leaf nodes

### ISSUE THREAD

**Issue by djsegal** [JuliaTeX/TreeView.jl#24]
Let's say you have a DAG representing a package and its dependencies, and their dependencies after them (and so forth).

What's the easiest way to hook into TreeView to plot that dependency graph? And is there a way to make the plot interactive with clicking on nodes?

Think it would be cool if you could keep clicking packages and the dag keeps switching root nodes.

// note that dependencies only appear once in a DAG (every other appearance is removed)

------

**[update:]** basically trying to replicate https://github.com/JuliaLang/julia/issues/25951#issuecomment-445156604

**Comment by djsegal** [comment]
Relatively simple example is:

```
- Dagger
  - Compat
  - MemPool
    - DataStructures
      - OrderedCollections
  - StatsBase
    - DataAPI
    - Missings
    - SortingAlgorithms
```

// note that `DataStructures` is also in `StatsBase`

**Comment by dpsanders** [comment]
I think you want to use TikzGraphs.jl for this directly, instead of TreeView
