### ISSUE TITLE
LaTeX error thrown if function name contains an underscore

### ISSUE THREAD

**Issue by mroavi** [JuliaTeX/TreeView.jl#29]
Minimal example:

```julia
using TreeView
@tree promote_type(Int64, Float64)
```
```
LabelledTree({3, 2} directed simple Int64 graph, Any[:promote_type, :Int64, :Float64])

! Missing $ inserted.
<inserted text> 
$
l.44 }
    ;
```

**Comment by dpsanders** [comment]
Good catch. 
Hopefully it should be easy enough to fix. Would you like to make a PR?

**Comment by mroavi** [comment]
Sure. I'll give it a shot.

**Comment by mroavi** [comment]
> Good catch.
> Hopefully it should be easy enough to fix. Would you like to make a PR?

Have you had a chance to look at the PR? Regards.
